# Generated by Django 5.1.1 on 2024-12-18 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_tc', models.IntegerField()),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_surname', models.CharField(max_length=50)),
                ('emp_phone', models.CharField(max_length=15)),
                ('profession', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_tc', models.IntegerField(unique=True)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_surname', models.CharField(max_length=50)),
                ('patient_phone', models.CharField(max_length=20)),
                ('patient_address', models.CharField(max_length=225)),
                ('patient_birthdate', models.DateField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reception.employee')),
                ('doc_name', models.CharField(max_length=50)),
                ('doc_title', models.CharField(max_length=255)),
                ('room_no', models.IntegerField(unique=True)),
                ('work_start', models.TimeField()),
                ('word_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Manages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.department')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorksIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField()),
                ('till', models.DateField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reception.department')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reception.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentMakes',
            fields=[
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.doctor')),
            ],
        ),
    ]
